version: '1.0'
services:
  serverless-app:
    build: 
      context: .
      dockerfile: Dockerfile
      # no-cache: true
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3005:3000"
    # command: serverless deploy
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY

volumes:
  node_modules:

